export const FETCH_Q_CATEGORY = 'FETCH_Q_CATEGORY';
export const FETCH_Q_QUESTIONS = 'FETCH_Q_QUESTIONS';
export const SELECTED_CATEGORY = 'SELECTED_CATEGORY';
export const CLEAR_QUESTIONS = 'CLEAR_QUESTIONS';

export const TOGGLE_Q_LOADING = 'TOGGLE_Q_LOADING';
export const SET_Q_ERROR = 'SET_Q_ERROR';
